Buffered Intercomponent Communication
Scrap-Mechanic-Logic-Consortium/SMLC-Standards pull request #4
Opened 2024-03-29 19:11 UTC by niknal357

This standard outlines the principles and mechanisms for buffered communication between components. (eg computer->computer, computer->network card, computer->screen, computer->device manager)

2024-04-03 11:36 UTC, endoddo requested changes
fixed typos

2024-04-03 11:36 UTC, endoddo commented on standards/buffered-intercomponent-communication.md
> +If the sender does not awknowledge the receiver's readiness (aka performs an unsafe push), the state of the communication may be damaged. In this case, the sender can send a reset signal through the
```suggestion
If the sender does not acknowledge the receiver's readiness (aka performs an unsafe push), the state of the communication may be damaged. In this case, the sender can send a reset signal through the RST line to reset the communication. Upon resetting, the receiver should clear its buffer and reset its state. Further actions can be taken by the receiver or higher level protocols which is up to implementation.
```

2024-04-03 11:36 UTC, endoddo commented on standards/buffered-intercomponent-communication.md
> +- The 32-bit data packet width was chosen for compatibility with a wide range of computers, devices, and usecases.
```suggestion
- The 32-bit data packet width was chosen for compatibility with a wide range of computers, devices, and use cases.
```

2024-04-03 12:12 UTC, endoddo commented on standards/buffered-intercomponent-communication.md
> +- Buffered Receivers: Maintain RTR at 1 while the buffer has ample space (10+ free packets). If space drops below 10 packets, pulse RTR x times per 10 ticks (x = number of free packets) to alert the
I think `pulse RTR x times oer 10 ticks` is misleading here. A single pulse would mean on then off so ten pulses would take 20 ticks. Here's a suggestion:
```suggestion
- Buffered Receivers: Maintain RTR at 1 while the buffer has ample space (10+ free packets). If space drops below 10 packets, set RTR to high for x ticks and then low again starting at every tenth tick (x = number of free packets) to alert the sender.
```

2024-04-18 10:23 UTC, codemaker4 commented
@niknal357 can you look at these changes please?

2024-04-18 22:34 UTC, merged